In [2]:
import pandas as pd
import os

In [16]:
path = os.getcwd()
path

inputPath = os.path.join(path,"DataSet.csv")
outputPath = os.path.join(path,"CleanedDataSet.csv")
imageFolderPath = os.path.join(path,"Images")

In [9]:
df = pd.read_csv(inputPath)
df.head()

,Global CMP22 (vent/cor) [W/m^2],Avg Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],dateTime
0,-0.982493,0.455,23.50,202401010000
1,-1.017650,0.000,0.00,202401010001
2,-1.011070,0.000,0.00,202401010002
3,-0.976800,0.000,0.00,202401010003
4,-0.976814,0.150,34.36,202401010004

In [11]:
df.head(20)

,Global CMP22 (vent/cor) [W/m^2],Avg Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],dateTime
0,-0.982493,0.455,23.50,202401010000
1,-1.017650,0.000,0.00,202401010001
2,-1.011070,0.000,0.00,202401010002
3,-0.976800,0.000,0.00,202401010003
4,-0.976814,0.150,34.36,202401010004
5,-0.985247,0.000,0.00,202401010005
6,-1.020840,0.000,0.00,202401010006
7,-1.033490,0.000,0.00,202401010007
8,-1.031030,0.000,0.00,202401010008
9,-1.020280,0.000,0.00,202401010009
10,-1.021580,0.000,0.00,202401010010
11,-1.017290,0.000,0.00,202401010011
12,-1.004340,0.000,0.00,202401010012
13,-0.979425,0.057,74.36,202401010013
14,-0.969167,0.067,73.12,202401010014
15,-0.959344,0.035,72.32,202401010015
16,-0.943666,0.000,0.00,202401010016
17,-0.940910,0.432,16.32,202401010017
18,-0.939551,0.490,9.56,202401010018
19,-0.922403,0.115,305.40,202401010019

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1052640 entries, 0 to 1052639
Data columns (total 4 columns):
 #   Column                                 Non-Null Count    Dtype
---  ------                                 --------------    -----
 0   Global CMP22 (vent/cor) [W/m^2]        1052640 non-null  float64
 1   Avg Wind Speed @ 6ft [m/s]             1052640 non-null  float64
 2   Avg Wind Direction @ 6ft [deg from N]  1052640 non-null  float64
 3   dateTime                               1052640 non-null  int64
dtypes: float64(3), int64(1)
memory usage: 32.1 MB

In [17]:
fileList = list(os.listdir(imageFolderPath))
fileList

['202401010700.jpg',
 '202401010710.jpg',
 '202401010720.jpg',
 '202401010730.jpg',
 '202401010740.jpg',
 '202401010750.jpg',
 '202401010800.jpg',
 '202401010810.jpg',
 '202401010820.jpg',
 '202401010830.jpg',
 '202401010840.jpg',
 '202401010850.jpg',
 '202401010900.jpg',
 '202401010910.jpg',
 '202401010920.jpg',
 '202401010930.jpg',
 '202401010940.jpg',
 '202401010950.jpg',
 '202401011000.jpg',
 '202401011010.jpg',
 '202401011020.jpg',
 '202401011030.jpg',
 '202401011040.jpg',
 '202401011200.jpg',
 '202401011210.jpg',
 '202401011220.jpg',
 '202401011230.jpg',
 '202401011240.jpg',
 '202401011250.jpg',
 '202401011300.jpg',
 '202401011310.jpg',
 '202401011320.jpg',
 '202401011330.jpg',
 '202401011340.jpg',
 '202401011350.jpg',
 '202401011400.jpg',
 '202401011410.jpg',
 '202401011420.jpg',
 '202401011430.jpg',
 '202401011440.jpg',
 '202401011450.jpg',
 '202401011500.jpg',
 '202401011510.jpg',
 '202401011520.jpg',
 '202401011530.jpg',
 '202401011540.jpg',
 '202401011550.jpg',
 '202401011600.jpg',
 '202401011610.jpg',
 '202401011620.jpg',
 '202401011630.jpg',
 '202401011640.jpg',
 '202401011650.jpg',
 '202401011710.jpg',
 '202401020700.jpg',
 '202401020710.jpg',
 '202401020720.jpg',
 '202401020730.jpg',
 '202401020740.jpg',
 '202401020750.jpg',
 '202401020800.jpg',
 '202401020810.jpg',
 '202401020820.jpg',
 '202401020830.jpg',
 '202401020840.jpg',
 '202401020850.jpg',
 '202401020900.jpg',
 '202401020910.jpg',
 '202401020920.jpg',
 '202401020930.jpg',
 '202401020940.jpg',
 '202401020950.jpg',
 '202401021000.jpg',
 '202401021010.jpg',
 '202401021020.jpg',
 '202401021030.jpg',
 '202401021040.jpg',
 '202401021050.jpg',
 '202401021100.jpg',
 '202401021110.jpg',
 '202401021150.jpg',
 '202401021200.jpg',
 '202401021210.jpg',
 '202401021220.jpg',
 '202401021230.jpg',
 '202401021240.jpg',
 '202401021250.jpg',
 '202401021300.jpg',
 '202401021310.jpg',
 '202401021320.jpg',
 '202401021330.jpg',
 '202401021340.jpg',
 '202401021350.jpg',
 '202401021400.jpg',
 '202401021410.jpg',
 '202401021420.jpg',
 '202401021430.jpg',
 '202401021440.jpg',
 '202401021450.jpg',
 '202401021500.jpg',
 '202401021510.jpg',
 '202401021520.jpg',
 '202401021530.jpg',
 '202401021540.jpg',
 '202401021550.jpg',
 '202401021600.jpg',
 '202401021610.jpg',
 '202401021620.jpg',
 '202401021630.jpg',
 '202401021640.jpg',
 '202401021650.jpg',
 '202401021710.jpg',
 '202401030700.jpg',
 '202401030710.jpg',
 '202401030720.jpg',
 '202401030730.jpg',
 '202401030740.jpg',
 '202401030750.jpg',
 '202401030800.jpg',
 '202401030810.jpg',
 '202401030820.jpg',
 '202401030830.jpg',
 '202401030840.jpg',
 '202401030850.jpg',
 '202401030900.jpg',
 '202401030910.jpg',
 '202401030920.jpg',
 '202401030930.jpg',
 '202401030940.jpg',
 '202401030950.jpg',
 '202401031000.jpg',
 '202401031010.jpg',
 '202401031100.jpg',
 '202401031110.jpg',
 '202401031120.jpg',
 '202401031130.jpg',
 '202401031140.jpg',
 '202401031150.jpg',
 '202401031200.jpg',
 '202401031210.jpg',
 '202401031220.jpg',
 '202401031230.jpg',
 '202401031240.jpg',
 '202401031250.jpg',
 '202401031300.jpg',
 '202401031310.jpg',
 '202401031320.jpg',
 '202401031330.jpg',
 '202401031340.jpg',
 '202401031350.jpg',
 '202401031400.jpg',
 '202401031410.jpg',
 '202401031420.jpg',
 '202401031430.jpg',
 '202401031440.jpg',
 '202401031450.jpg',
 '202401031500.jpg',
 '202401031500.zip',
 '202401031510.jpg',
 '202401031520.jpg',
 '202401031530.jpg',
 '202401031540.jpg',
 '202401031550.jpg',
 '202401031600.jpg',
 '202401031610.jpg',
 '202401031620.jpg',
 '202401031630.jpg',
 '202401031640.jpg',
 '202401031650.jpg',
 '202401031710.jpg',
 '202401040700.jpg',
 '202401040710.jpg',
 '202401040720.jpg',
 '202401040730.jpg',
 '202401040740.jpg',
 '202401040750.jpg',
 '202401040800.jpg',
 '202401040810.jpg',
 '202401040820.jpg',
 '202401040830.jpg',
 '202401040840.jpg',
 '202401040850.jpg',
 '202401040900.jpg',
 '202401040910.jpg',
 '202401040920.jpg',
 '202401040930.jpg',
 '202401040940.jpg',
 '202401040950.jpg',
 '202401041000.jpg',
 '202401041010.jpg',
 '202401041020.jpg',
 '202401041030.jpg',
 '202401041040.jpg',
 '202401041050.jpg',
 '202401041100.jpg',
 '202401041110.jpg',
 '202401041150.jpg',
 '202401041200.jpg',
 '202401041210.jpg',
 '202401041220.jpg',
 '202401041230.jpg',
 '202401041240.jpg',
 '202401041250.jpg',
 '202401041300.jpg',
 '202401041310.jpg',
 '202401041320.jpg',
 '202401041330.jpg',
 '202401041340.jpg',
 '202401041350.jpg',
 '202401041400.jpg',
 '202401041410.jpg',
 '202401041420.jpg',
 '202401041430.jpg',
 '202401041440.jpg',
 '202401041450.jpg',
 '202401041500.jpg',
 '202401041510.jpg',
 '202401041520.jpg',
 '202401041530.jpg',
 '202401041540.jpg',
 '202401041550.jpg',
 '202401041600.jpg',
 '202401041610.jpg',
 '202401041620.jpg',
 '202401041630.jpg',
 '202401041640.jpg',
 '202401041650.jpg',
 '202401041710.jpg',
 '202401050700.jpg',
 '202401050710.jpg',
 '202401050720.jpg',
 '202401050730.jpg',
 '202401050740.jpg',
 '202401050750.jpg',
 '202401050800.jpg',
 '202401050810.jpg',
 '202401050820.jpg',
 '202401050830.jpg',
 '202401050840.jpg',
 '202401050850.jpg',
 '202401050900.jpg',
 '202401050910.jpg',
 '202401050920.jpg',
 '202401050930.jpg',
 '202401050940.jpg',
 '202401050950.jpg',
 '202401051000.jpg',
 '202401051010.jpg',
 '202401051140.jpg',
 '202401051150.jpg',
 '202401051200.jpg',
 '202401051210.jpg',
 '202401051220.jpg',
 '202401051230.jpg',
 '202401051240.jpg',
 '202401051250.jpg',
 '202401051300.jpg',
 '202401051310.jpg',
 '202401051320.jpg',
 '202401051330.jpg',
 '202401051340.jpg',
 '202401051350.jpg',
 '202401051400.jpg',
 '202401051410.jpg',
 '202401051420.jpg',
 '202401051430.jpg',
 '202401051440.jpg',
 '202401051450.jpg',
 '202401051500.jpg',
 '202401051510.jpg',
 '202401051520.jpg',
 '202401051530.jpg',
 '202401051540.jpg',
 '202401051550.jpg',
 '202401051600.jpg',
 '202401051610.jpg',
 '202401051620.jpg',
 '202401051630.jpg',
 '202401051640.jpg',
 '202401051650.jpg',
 '202401051710.jpg',
 '202401060700.jpg',
 '202401060710.jpg',
 '202401060720.jpg',
 '202401060730.jpg',
 '202401060740.jpg',
 '202401060750.jpg',
 '202401060800.jpg',
 '202401060810.jpg',
 '202401060820.jpg',
 '202401060830.jpg',
 '202401060840.jpg',
 '202401060850.jpg',
 '202401060900.jpg',
 '202401060910.jpg',
 '202401060920.jpg',
 '202401060930.jpg',
 '202401060940.jpg',
 '202401060950.jpg',
 '202401061000.jpg',
 '202401061010.jpg',
 '202401061020.jpg',
 '202401061030.jpg',
 '202401061040.jpg',
 '202401061120.jpg',
 '202401061130.jpg',
 '202401061140.jpg',
 '202401061150.jpg',
 '202401061200.jpg',
 '202401061210.jpg',
 '202401061220.jpg',
 '202401061230.jpg',
 '202401061240.jpg',
 '202401061250.jpg',
 '202401061300.jpg',
 '202401061310.jpg',
 '202401061320.jpg',
 '202401061330.jpg',
 '202401061340.jpg',
 '202401061350.jpg',
 '202401061400.jpg',
 '202401061410.jpg',
 '202401061420.jpg',
 '202401061430.jpg',
 '202401061440.jpg',
 '202401061450.jpg',
 '202401061500.jpg',
 '202401061510.jpg',
 '202401061520.jpg',
 '202401061530.jpg',
 '202401061540.jpg',
 '202401061550.jpg',
 '202401061600.jpg',
 '202401061610.jpg',
 '202401061620.jpg',
 '202401061630.jpg',
 '202401061640.jpg',
 '202401061650.jpg',
 '202401061710.jpg',
 '202401061720.jpg',
 '202401070700.jpg',
 '202401070710.jpg',
 '202401070720.jpg',
 '202401070730.jpg',
 '202401070740.jpg',
 '202401070750.jpg',
 '202401070800.jpg',
 '202401070810.jpg',
 '202401070820.jpg',
 '202401070830.jpg',
 '202401070840.jpg',
 '202401070850.jpg',
 '202401070900.jpg',
 '202401070910.jpg',
 '202401070920.jpg',
 '202401070930.jpg',
 '202401070940.jpg',
 '202401070950.jpg',
 '202401071000.jpg',
 '202401071010.jpg',
 '202401071020.jpg',
 '202401071030.jpg',
 '202401071040.jpg',
 '202401071050.jpg',
 '202401071100.jpg',
 '202401071110.jpg',
 '202401071240.jpg',
 '202401071250.jpg',
 '202401071300.jpg',
 '202401071310.jpg',
 '202401071320.jpg',
 '202401071330.jpg',
 '202401071340.jpg',
 '202401071350.jpg',
 '202401071400.jpg',
 '202401071410.jpg',
 '202401071420.jpg',
 '202401071430.jpg',
 '202401071440.jpg',
 '202401071450.jpg',
 '202401071500.jpg',
 '202401071510.jpg',
 '202401071520.jpg',
 '202401071530.jpg',
 '202401071540.jpg',
 '202401071550.jpg',
 '202401071600.jpg',
 '202401071610.jpg',
 '202401071620.jpg',
 '202401071630.jpg',
 '202401071640.jpg',
 '202401071650.jpg',
 '202401071710.jpg',
 '202401071720.jpg',
 '202401080700.jpg',
 '202401080710.jpg',
 '202401080720.jpg',
 '202401080730.jpg',
 '202401080740.jpg',
 '202401080750.jpg',
 '202401080800.jpg',
 '202401080810.jpg',
 '202401080820.jpg',
 '202401080830.jpg',
 '202401080840.jpg',
 '202401080850.jpg',
 '202401080900.jpg',
 '202401080910.jpg',
 '202401080920.jpg',
 '202401080930.jpg',
 '202401080940.jpg',
 '202401080950.jpg',
 '202401081000.jpg',
 '202401081010.jpg',
 '202401081020.jpg',
 '202401081030.jpg',
 '202401081040.jpg',
 '202401081050.jpg',
 '202401081100.jpg',
 '202401081110.jpg',
 '202401081120.jpg',
 '202401081130.jpg',
 '202401081140.jpg',
 '202401081300.jpg',
 '202401081310.jpg',
 '202401081320.jpg',
 '202401081330.jpg',
 '202401081340.jpg',
 '202401081350.jpg',
 '202401081400.jpg',
 '202401081410.jpg',
 '202401081420.jpg',
 '202401081430.jpg',
 '202401081440.jpg',
 '202401081450.jpg',
 '202401081500.jpg',
 '202401081510.jpg',
 '202401081520.jpg',
 '202401081530.jpg',
 '202401081540.jpg',
 '202401081550.jpg',
 '202401081600.jpg',
 '202401081610.jpg',
 '202401081620.jpg',
 '202401081630.jpg',
 '202401081640.jpg',
 '202401081650.jpg',
 '202401081710.jpg',
 '202401081720.jpg',
 '202401090700.jpg',
 '202401090710.jpg',
 '202401090720.jpg',
 '202401090730.jpg',
 '202401090740.jpg',
 '202401090750.jpg',
 '202401090800.jpg',
 '202401090810.jpg',
 '202401090820.jpg',
 '202401090830.jpg',
 '202401090840.jpg',
 '202401090850.jpg',
 '202401090900.jpg',
 '202401090910.jpg',
 '202401090920.jpg',
 '202401090930.jpg',
 '202401090940.jpg',
 '202401090950.jpg',
 '202401091000.jpg',
 '202401091010.jpg',
 '202401091020.jpg',
 '202401091030.jpg',
 '202401091040.jpg',
 '202401091050.jpg',
 '202401091100.jpg',
 '202401091110.jpg',
 '202401091150.jpg',
 '202401091200.jpg',
 '202401091210.jpg',
 '202401091220.jpg',
 '202401091230.jpg',
 '202401091240.jpg',
 '202401091250.jpg',
 '202401091300.jpg',
 '202401091310.jpg',
 '202401091320.jpg',
 '202401091330.jpg',
 '202401091340.jpg',
 '202401091350.jpg',
 '202401091400.jpg',
 '202401091410.jpg',
 '202401091420.jpg',
 '202401091430.jpg',
 '202401091440.jpg',
 '202401091450.jpg',
 '202401091500.jpg',
 '202401091510.jpg',
 '202401091520.jpg',
 '202401091530.jpg',
 '202401091540.jpg',
 '202401091550.jpg',
 '202401091600.jpg',
 '202401091610.jpg',
 '202401091620.jpg',
 '202401091630.jpg',
 '202401091640.jpg',
 '202401091650.jpg',
 '202401091710.jpg',
 '202401091720.jpg',
 '202401100700.jpg',
 '202401100710.jpg',
 '202401100720.jpg',
 '202401100730.jpg',
 '202401100740.jpg',
 '202401100750.jpg',
 '202401100800.jpg',
 '202401100810.jpg',
 '202401100820.jpg',
 '202401100830.jpg',
 '202401100840.jpg',
 '202401100850.jpg',
 '202401100900.jpg',
 '202401100910.jpg',
 '202401100920.jpg',
 '202401100930.jpg',
 '202401100940.jpg',
 '202401100950.jpg',
 '202401101000.jpg',
 '202401101010.jpg',
 '202401101020.jpg',
 '202401101030.jpg',
 '202401101040.jpg',
 '202401101210.jpg',
 '202401101220.jpg',
 '202401101230.jpg',
 '202401101240.jpg',
 '202401101250.jpg',
 '202401101300.jpg',
 '202401101310.jpg',
 '202401101320.jpg',
 '202401101330.jpg',
 '202401101340.jpg',
 '202401101350.jpg',
 '202401101400.jpg',
 '202401101410.jpg',
 '202401101420.jpg',
 '202401101430.jpg',
 '202401101440.jpg',
 '202401101450.jpg',
 '202401101500.jpg',
 '202401101510.jpg',
 '202401101520.jpg',
 '202401101530.jpg',
 '202401101540.jpg',
 '202401101550.jpg',
 '202401101600.jpg',
 '202401101610.jpg',
 '202401101620.jpg',
 '202401101630.jpg',
 '202401101640.jpg',
 '202401101650.jpg',
 '202401101710.jpg',
 '202401101720.jpg',
 '202401110700.jpg',
 '202401110710.jpg',
 '202401110720.jpg',
 '202401110730.jpg',
 '202401110740.jpg',
 '202401110750.jpg',
 '202401110800.jpg',
 '202401110810.jpg',
 '202401110820.jpg',
 '202401110830.jpg',
 '202401110840.jpg',
 '202401110850.jpg',
 '202401110900.jpg',
 '202401110910.jpg',
 '202401110920.jpg',
 '202401110930.jpg',
 '202401110940.jpg',
 '202401111110.jpg',
 '202401111120.jpg',
 '202401111130.jpg',
 '202401111140.jpg',
 '202401111150.jpg',
 '202401111200.jpg',
 '202401111210.jpg',
 '202401111220.jpg',
 '202401111230.jpg',
 '202401111240.jpg',
 '202401111250.jpg',
 '202401111300.jpg',
 '202401111310.jpg',
 '202401111320.jpg',
 '202401111330.jpg',
 '202401111340.jpg',
 '202401111350.jpg',
 '202401111400.jpg',
 '202401111410.jpg',
 '202401111420.jpg',
 '202401111430.jpg',
 '202401111440.jpg',
 '202401111450.jpg',
 '202401111500.jpg',
 '202401111510.jpg',
 '202401111520.jpg',
 '202401111530.jpg',
 '202401111540.jpg',
 '202401111550.jpg',
 '202401111600.jpg',
 '202401111610.jpg',
 '202401111620.jpg',
 '202401111630.jpg',
 '202401111640.jpg',
 '202401111650.jpg',
 '202401111710.jpg',
 '202401111720.jpg',
 '202401120700.jpg',
 '202401120710.jpg',
 '202401120720.jpg',
 '202401120730.jpg',
 '202401120740.jpg',
 '202401120750.jpg',
 '202401120800.jpg',
 '202401120810.jpg',
 '202401120820.jpg',
 '202401120830.jpg',
 '202401120840.jpg',
 '202401120850.jpg',
 '202401120900.jpg',
 '202401120910.jpg',
 '202401120920.jpg',
 '202401120930.jpg',
 '202401120940.jpg',
 '202401120950.jpg',
 '202401121000.jpg',
 '202401121010.jpg',
 '202401121020.jpg',
 '202401121030.jpg',
 '202401121040.jpg',
 '202401121200.jpg',
 '202401121210.jpg',
 '202401121220.jpg',
 '202401121230.jpg',
 '202401121240.jpg',
 '202401121250.jpg',
 '202401121300.jpg',
 '202401121310.jpg',
 '202401121320.jpg',
 '202401121330.jpg',
 '202401121340.jpg',
 '202401121350.jpg',
 '202401121400.jpg',
 '202401121410.jpg',
 '202401121420.jpg',
 '202401121430.jpg',
 '202401121440.jpg',
 '202401121450.jpg',
 '202401121500.jpg',
 '202401121510.jpg',
 '202401121520.jpg',
 '202401121530.jpg',
 '202401121540.jpg',
 '202401121550.jpg',
 '202401121600.jpg',
 '202401121610.jpg',
 '202401121620.jpg',
 '202401121630.jpg',
 '202401121640.jpg',
 '202401121650.jpg',
 '202401121710.jpg',
 '202401121720.jpg',
 '202401130650.jpg',
 '202401130700.jpg',
 '202401130710.jpg',
 '202401130720.jpg',
 '202401130730.jpg',
 '202401130740.jpg',
 '202401130750.jpg',
 '202401130800.jpg',
 '202401130810.jpg',
 '202401130820.jpg',
 '202401130830.jpg',
 '202401130840.jpg',
 '202401130850.jpg',
 '202401130900.jpg',
 '202401130910.jpg',
 '202401130920.jpg',
 '202401130930.jpg',
 '202401130940.jpg',
 '202401130950.jpg',
 '202401131000.jpg',
 '202401131010.jpg',
 '202401131020.jpg',
 '202401131030.jpg',
 '202401131040.jpg',
 '202401131050.jpg',
 '202401131100.jpg',
 '202401131110.jpg',
 '202401131120.jpg',
 '202401131130.jpg',
 '202401131310.jpg',
 '202401131320.jpg',
 '202401131330.jpg',
 '202401131340.jpg',
 '202401131350.jpg',
 '202401131400.jpg',
 '202401131410.jpg',
 '202401131420.jpg',
 '202401131430.jpg',
 '202401131440.jpg',
 '202401131450.jpg',
 '202401131500.jpg',
 '202401131510.jpg',
 '202401131520.jpg',
 '202401131530.jpg',
 '202401131540.jpg',
 '202401131550.jpg',
 '202401131600.jpg',
 '202401131610.jpg',
 '202401131620.jpg',
 '202401131630.jpg',
 '202401131640.jpg',
 '202401131650.jpg',
 '202401131710.jpg',
 '202401131720.jpg',
 '202401140650.jpg',
 '202401140700.jpg',
 '202401140710.jpg',
 '202401140720.jpg',
 '202401140730.jpg',
 '202401140740.jpg',
 '202401140750.jpg',
 '202401140800.jpg',
 '202401140810.jpg',
 '202401140820.jpg',
 '202401140830.jpg',
 '202401140840.jpg',
 '202401140850.jpg',
 '202401140900.jpg',
 '202401140910.jpg',
 '202401140920.jpg',
 '202401140930.jpg',
 '202401140940.jpg',
 '202401140950.jpg',
 '202401141000.jpg',
 '202401141010.jpg',
 '202401141020.jpg',
 '202401141030.jpg',
 '202401141040.jpg',
 '202401141050.jpg',
 '202401141100.jpg',
 '202401141110.jpg',
 '202401141120.jpg',
 '202401141130.jpg',
 '202401141250.jpg',
 '202401141300.jpg',
 '202401141310.jpg',
 '202401141320.jpg',
 '202401141330.jpg',
 '202401141340.jpg',
 '202401141350.jpg',
 '202401141400.jpg',
 '202401141410.jpg',
 '202401141420.jpg',
 '202401141430.jpg',
 '202401141440.jpg',
 '202401141450.jpg',
 '202401141500.jpg',
 '202401141510.jpg',
 '202401141520.jpg',
 '202401141530.jpg',
 '202401141540.jpg',
 '202401141550.jpg',
 '202401141600.jpg',
 '202401141610.jpg',
 '202401141620.jpg',
 '202401141630.jpg',
 '202401141640.jpg',
 '202401141650.jpg',
 '202401141710.jpg',
 '202401141720.jpg',
 '202401150650.jpg',
 '202401150700.jpg',
 '202401150710.jpg',
 '202401150720.jpg',
 '202401150730.jpg',
 '202401150740.jpg',
 '202401150750.jpg',
 '202401150800.jpg',
 '202401150810.jpg',
 '202401150820.jpg',
 '202401150830.jpg',
 '202401150840.jpg',
 '202401150850.jpg',
 '202401150900.jpg',
 '202401150910.jpg',
 '202401150920.jpg',
 '202401150930.jpg',
 '202401150940.jpg',
 '202401150950.jpg',
 '202401151000.jpg',
 '202401151010.jpg',
 '202401151020.jpg',
 '202401151030.jpg',
 '202401151150.jpg',
 '202401151200.jpg',
 '202401151210.jpg',
 '202401151220.jpg',
 '202401151230.jpg',
 '202401151240.jpg',
 '202401151250.jpg',
 '202401151300.jpg',
 '202401151310.jpg',
 '202401151320.jpg',
 '202401151330.jpg',
 '202401151340.jpg',
 '202401151350.jpg',
 '202401151400.jpg',
 '202401151410.jpg',
 '202401151420.jpg',
 '202401151430.jpg',
 '202401151440.jpg',
 '202401151450.jpg',
 '202401151500.jpg',
 '202401151510.jpg',
 '202401151520.jpg',
 '202401151530.jpg',
 '202401151540.jpg',
 '202401151550.jpg',
 '202401151600.jpg',
 '202401151610.jpg',
 '202401151620.jpg',
 '202401151630.jpg',
 '202401151640.jpg',
 '202401151650.jpg',
 '202401151710.jpg',
 '202401151720.jpg',
 '202401160650.jpg',
 '202401160700.jpg',
 '202401160710.jpg',
 '202401160720.jpg',
 '202401160730.jpg',
 '202401160740.jpg',
 '202401160750.jpg',
 '202401160800.jpg',
 '202401160810.jpg',
 '202401160820.jpg',
 '202401160830.jpg',
 '202401160840.jpg',
 '202401160850.jpg',
 '202401160900.jpg',
 '202401160910.jpg',
 '202401160920.jpg',
 '202401160930.jpg',
 '202401160940.jpg',
 '202401160950.jpg',
 '202401161000.jpg',
 '202401161130.jpg',
 '202401161140.jpg',
 '202401161150.jpg',
 '202401161200.jpg',
 '202401161210.jpg',
 '202401161220.jpg',
 '202401161230.jpg',
 '202401161240.jpg',
 '202401161250.jpg',
 '202401161300.jpg',
 '202401161310.jpg',
 '202401161320.jpg',
 '202401161330.jpg',
 '202401161340.jpg',
 '202401161350.jpg',
 '202401161400.jpg',
 '202401161410.jpg',
 '202401161420.jpg',
 '202401161430.jpg',
 '202401161440.jpg',
 '202401161450.jpg',
 '202401161500.jpg',
 '202401161510.jpg',
 '202401161520.jpg',
 '202401161530.jpg',
 '202401161540.jpg',
 '202401161550.jpg',
 '202401161600.jpg',
 '202401161610.jpg',
 '202401161620.jpg',
 '202401161630.jpg',
 '202401161640.jpg',
 '202401161650.jpg',
 '202401161710.jpg',
 '202401161720.jpg',
 '202401161730.jpg',
 '202401170650.jpg',
 '202401170700.jpg',
 '202401170710.jpg',
 '202401170720.jpg',
 '202401170730.jpg',
 '202401170740.jpg',
 '202401170750.jpg',
 '202401170800.jpg',
 '202401170810.jpg',
 '202401170820.jpg',
 '202401170830.jpg',
 '202401170840.jpg',
 '202401170850.jpg',
 '202401170900.jpg',
 '202401170910.jpg',
 '202401170920.jpg',
 '202401170930.jpg',
 '202401170940.jpg',
 '202401170950.jpg',
 '202401171000.jpg',
 '202401171050.jpg',
 '202401171100.jpg',
 '202401171110.jpg',
 '202401171120.jpg',
 '202401171130.jpg',
 '202401171140.jpg',
 '202401171150.jpg',
 '202401171200.jpg',
 '202401171210.jpg',
 '202401171220.jpg',
 '202401171230.jpg',
 '202401171240.jpg',
 '202401171250.jpg',
 '202401171300.jpg',
 '202401171310.jpg',
 '202401171320.jpg',
 '202401171330.jpg',
 '202401171340.jpg',
 '202401171350.jpg',
 '202401171400.jpg',
 '202401171410.jpg',
 '202401171420.jpg',
 '202401171430.jpg',
 '202401171440.jpg',
 '202401171450.jpg',
 '202401171500.jpg',
 '202401171510.jpg',
 '202401171520.jpg',
 '202401171530.jpg',
 '202401171540.jpg',
 '202401171550.jpg',
 '202401171600.jpg',
 '202401171610.jpg',
 '202401171620.jpg',
 '202401171630.jpg',
 '202401171640.jpg',
 '202401171650.jpg',
 '202401171710.jpg',
 '202401171720.jpg',

In [18]:
df["dateTime"] =  df["dateTime"].astype("str")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1052640 entries, 0 to 1052639
Data columns (total 4 columns):
 #   Column                                 Non-Null Count    Dtype
---  ------                                 --------------    -----
 0   Global CMP22 (vent/cor) [W/m^2]        1052640 non-null  float64
 1   Avg Wind Speed @ 6ft [m/s]             1052640 non-null  float64
 2   Avg Wind Direction @ 6ft [deg from N]  1052640 non-null  float64
 3   dateTime                               1052640 non-null  object
dtypes: float64(3), object(1)
memory usage: 32.1+ MB

In [20]:
df["Image"] = df["dateTime"].isin(fileList)
df["Image"]

0          False
1          False
2          False
3          False
4          False
           ...
1052635    False
1052636    False
1052637    False
1052638    False
1052639    False
Name: Image, Length: 1052640, dtype: bool

In [21]:
for i in range(len(fileList)):
    fileList[i] = fileList[i][:12]
fileList[:10]

['202401010700',
 '202401010710',
 '202401010720',
 '202401010730',
 '202401010740',
 '202401010750',
 '202401010800',
 '202401010810',
 '202401010820',
 '202401010830']

In [22]:
df["Image"] = df["dateTime"].isin(fileList)
df["Image"].value_counts()

Image
False    1008573
True       44067
Name: count, dtype: int64

In [23]:
df_temp = df.copy()

In [24]:
df = df[df["Image"] == True]
df.head()

,Global CMP22 (vent/cor) [W/m^2],Avg Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],dateTime,Image
420,-0.639780,2.950,304.0,202401010700,True
430,0.648148,2.963,290.4,202401010710,True
440,3.620890,2.638,302.5,202401010720,True
450,13.680000,2.275,291.1,202401010730,True
460,29.144100,1.688,289.1,202401010740,True

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44067 entries, 420 to 1052200
Data columns (total 5 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Global CMP22 (vent/cor) [W/m^2]        44067 non-null  float64
 1   Avg Wind Speed @ 6ft [m/s]             44067 non-null  float64
 2   Avg Wind Direction @ 6ft [deg from N]  44067 non-null  float64
 3   dateTime                               44067 non-null  object
 4   Image                                  44067 non-null  bool
dtypes: bool(1), float64(3), object(1)
memory usage: 1.7+ MB

In [28]:
df.rename(columns={"Global CMP22 (vent/cor) [W/m^2]":"irradiance","Avg Wind Speed @ 6ft [m/s]":"WindSpeed","Avg Wind Direction @ 6ft [deg from N]":"WindDirection"},inplace=True)

In [30]:

df.to_csv(outputPath,index=False)