In [1]:
import pandas as pd
import os

In [3]:
df = pd.read_csv(r"C:\Study\IPD_Solar_Tracking\Dataset\DataSet.csv")
df.head()

,Global CMP22 (vent/cor) [W/m^2],Avg Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],dateTime
0,-0.982493,0.455,23.50,202401010000
1,-1.017650,0.000,0.00,202401010001
2,-1.011070,0.000,0.00,202401010002
3,-0.976800,0.000,0.00,202401010003
4,-0.976814,0.150,34.36,202401010004

In [4]:
df.head(20)

,Global CMP22 (vent/cor) [W/m^2],Avg Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],dateTime
0,-0.982493,0.455,23.50,202401010000
1,-1.017650,0.000,0.00,202401010001
2,-1.011070,0.000,0.00,202401010002
3,-0.976800,0.000,0.00,202401010003
4,-0.976814,0.150,34.36,202401010004
5,-0.985247,0.000,0.00,202401010005
6,-1.020840,0.000,0.00,202401010006
7,-1.033490,0.000,0.00,202401010007
8,-1.031030,0.000,0.00,202401010008
9,-1.020280,0.000,0.00,202401010009
10,-1.021580,0.000,0.00,202401010010
11,-1.017290,0.000,0.00,202401010011
12,-1.004340,0.000,0.00,202401010012
13,-0.979425,0.057,74.36,202401010013
14,-0.969167,0.067,73.12,202401010014
15,-0.959344,0.035,72.32,202401010015
16,-0.943666,0.000,0.00,202401010016
17,-0.940910,0.432,16.32,202401010017
18,-0.939551,0.490,9.56,202401010018
19,-0.922403,0.115,305.40,202401010019

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1052640 entries, 0 to 1052639
Data columns (total 4 columns):
 #   Column                                 Non-Null Count    Dtype
---  ------                                 --------------    -----
 0   Global CMP22 (vent/cor) [W/m^2]        1052640 non-null  float64
 1   Avg Wind Speed @ 6ft [m/s]             1052640 non-null  float64
 2   Avg Wind Direction @ 6ft [deg from N]  1052640 non-null  float64
 3   dateTime                               1052640 non-null  int64
dtypes: float64(3), int64(1)
memory usage: 32.1 MB

In [11]:
fileList = list(os.listdir(r"C:\Study\IPD_Solar_Tracking\Dataset\Images"))
fileList

['202401010700.jpg',
 '202401010710.jpg',
 '202401010720.jpg',
 '202401010730.jpg',
 '202401010740.jpg',
 '202401010750.jpg',
 '202401010800.jpg',
 '202401010810.jpg',
 '202401010820.jpg',
 '202401010830.jpg',
 '202401010840.jpg',
 '202401010850.jpg',
 '202401010900.jpg',
 '202401010910.jpg',
 '202401010920.jpg',
 '202401010930.jpg',
 '202401010940.jpg',
 '202401010950.jpg',
 '202401011000.jpg',
 '202401011010.jpg',
 '202401011020.jpg',
 '202401011030.jpg',
 '202401011040.jpg',
 '202401011200.jpg',
 '202401011210.jpg',
 '202401011220.jpg',
 '202401011230.jpg',
 '202401011240.jpg',
 '202401011250.jpg',
 '202401011300.jpg',
 '202401011310.jpg',
 '202401011320.jpg',
 '202401011330.jpg',
 '202401011340.jpg',
 '202401011350.jpg',
 '202401011400.jpg',
 '202401011410.jpg',
 '202401011420.jpg',
 '202401011430.jpg',
 '202401011440.jpg',
 '202401011450.jpg',
 '202401011500.jpg',
 '202401011510.jpg',
 '202401011520.jpg',
 '202401011530.jpg',
 '202401011540.jpg',
 '202401011550.jpg',
 '202401011600.jpg',
 '202401011610.jpg',
 '202401011620.jpg',
 '202401011630.jpg',
 '202401011640.jpg',
 '202401011650.jpg',
 '202401011710.jpg',
 '202401020700.jpg',
 '202401020710.jpg',
 '202401020720.jpg',
 '202401020730.jpg',
 '202401020740.jpg',
 '202401020750.jpg',
 '202401020800.jpg',
 '202401020810.jpg',
 '202401020820.jpg',
 '202401020830.jpg',
 '202401020840.jpg',
 '202401020850.jpg',
 '202401020900.jpg',
 '202401020910.jpg',
 '202401020920.jpg',
 '202401020930.jpg',
 '202401020940.jpg',
 '202401020950.jpg',
 '202401021000.jpg',
 '202401021010.jpg',
 '202401021020.jpg',
 '202401021030.jpg',
 '202401021040.jpg',
 '202401021050.jpg',
 '202401021100.jpg',
 '202401021110.jpg',
 '202401021150.jpg',
 '202401021200.jpg',
 '202401021210.jpg',
 '202401021220.jpg',
 '202401021230.jpg',
 '202401021240.jpg',
 '202401021250.jpg',
 '202401021300.jpg',
 '202401021310.jpg',
 '202401021320.jpg',
 '202401021330.jpg',
 '202401021340.jpg',
 '202401021350.jpg',
 '202401021400.jpg',
 '202401021410.jpg',
 '202401021420.jpg',
 '202401021430.jpg',
 '202401021440.jpg',
 '202401021450.jpg',
 '202401021500.jpg',
 '202401021510.jpg',
 '202401021520.jpg',
 '202401021530.jpg',
 '202401021540.jpg',
 '202401021550.jpg',
 '202401021600.jpg',
 '202401021610.jpg',
 '202401021620.jpg',
 '202401021630.jpg',
 '202401021640.jpg',
 '202401021650.jpg',
 '202401021710.jpg',
 '202401030700.jpg',
 '202401030710.jpg',
 '202401030720.jpg',
 '202401030730.jpg',
 '202401030740.jpg',
 '202401030750.jpg',
 '202401030800.jpg',
 '202401030810.jpg',
 '202401030820.jpg',
 '202401030830.jpg',
 '202401030840.jpg',
 '202401030850.jpg',
 '202401030900.jpg',
 '202401030910.jpg',
 '202401030920.jpg',
 '202401030930.jpg',
 '202401030940.jpg',
 '202401030950.jpg',
 '202401031000.jpg',
 '202401031010.jpg',
 '202401031100.jpg',
 '202401031110.jpg',
 '202401031120.jpg',
 '202401031130.jpg',
 '202401031140.jpg',
 '202401031150.jpg',
 '202401031200.jpg',
 '202401031210.jpg',
 '202401031220.jpg',
 '202401031230.jpg',
 '202401031240.jpg',
 '202401031250.jpg',
 '202401031300.jpg',
 '202401031310.jpg',
 '202401031320.jpg',
 '202401031330.jpg',
 '202401031340.jpg',
 '202401031350.jpg',
 '202401031400.jpg',
 '202401031410.jpg',
 '202401031420.jpg',
 '202401031430.jpg',
 '202401031440.jpg',
 '202401031450.jpg',
 '202401031500.jpg',
 '202401031510.jpg',
 '202401031520.jpg',
 '202401031530.jpg',
 '202401031540.jpg',
 '202401031550.jpg',
 '202401031600.jpg',
 '202401031610.jpg',
 '202401031620.jpg',
 '202401031630.jpg',
 '202401031640.jpg',
 '202401031650.jpg',
 '202401031710.jpg',
 '202401040700.jpg',
 '202401040710.jpg',
 '202401040720.jpg',
 '202401040730.jpg',
 '202401040740.jpg',
 '202401040750.jpg',
 '202401040800.jpg',
 '202401040810.jpg',
 '202401040820.jpg',
 '202401040830.jpg',
 '202401040840.jpg',
 '202401040850.jpg',
 '202401040900.jpg',
 '202401040910.jpg',
 '202401040920.jpg',
 '202401040930.jpg',
 '202401040940.jpg',
 '202401040950.jpg',
 '202401041000.jpg',
 '202401041010.jpg',
 '202401041020.jpg',
 '202401041030.jpg',
 '202401041040.jpg',
 '202401041050.jpg',
 '202401041100.jpg',
 '202401041110.jpg',
 '202401041150.jpg',
 '202401041200.jpg',
 '202401041210.jpg',
 '202401041220.jpg',
 '202401041230.jpg',
 '202401041240.jpg',
 '202401041250.jpg',
 '202401041300.jpg',
 '202401041310.jpg',
 '202401041320.jpg']

In [12]:
df["dateTime"] =  df["dateTime"].astype("str")

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1052640 entries, 0 to 1052639
Data columns (total 4 columns):
 #   Column                                 Non-Null Count    Dtype
---  ------                                 --------------    -----
 0   Global CMP22 (vent/cor) [W/m^2]        1052640 non-null  float64
 1   Avg Wind Speed @ 6ft [m/s]             1052640 non-null  float64
 2   Avg Wind Direction @ 6ft [deg from N]  1052640 non-null  float64
 3   dateTime                               1052640 non-null  str
dtypes: float64(3), str(1)
memory usage: 32.1 MB

In [14]:

df["Image"] = df["dateTime"].isin(fileList)
df["Image"]

0          False
1          False
2          False
3          False
4          False
           ...
1052635    False
1052636    False
1052637    False
1052638    False
1052639    False
Name: Image, Length: 1052640, dtype: bool

In [15]:
for i in range(len(fileList)):
    fileList[i] = fileList[i][:12]
fileList[:10]

['202401010700',
 '202401010710',
 '202401010720',
 '202401010730',
 '202401010740',
 '202401010750',
 '202401010800',
 '202401010810',
 '202401010820',
 '202401010830']

In [16]:
df["Image"] = df["dateTime"].isin(fileList)
df["Image"].value_counts()

Image
False    1052435
True         205
Name: count, dtype: int64

In [17]:
df_temp = df.copy()

In [18]:
df = df[df["Image"] == True]
df.head()

,Global CMP22 (vent/cor) [W/m^2],Avg Wind Speed @ 6ft [m/s],Avg Wind Direction @ 6ft [deg from N],dateTime,Image
420,-0.639780,2.950,304.0,202401010700,True
430,0.648148,2.963,290.4,202401010710,True
440,3.620890,2.638,302.5,202401010720,True
450,13.680000,2.275,291.1,202401010730,True
460,29.144100,1.688,289.1,202401010740,True

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 205 entries, 420 to 5120
Data columns (total 5 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Global CMP22 (vent/cor) [W/m^2]        205 non-null    float64
 1   Avg Wind Speed @ 6ft [m/s]             205 non-null    float64
 2   Avg Wind Direction @ 6ft [deg from N]  205 non-null    float64
 3   dateTime                               205 non-null    str
 4   Image                                  205 non-null    bool
dtypes: bool(1), float64(3), str(1)
memory usage: 8.2 KB

In [21]:
df.to_csv(r"C:\Study\IPD_Solar_Tracking\Dataset\CleanedDataSet.csv")